version: '3'
services:
  mongo:
    image: mongo:3.6
    restart: "no"
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo:
